name: pr review

on:
  pull_request:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_NUMBER: ${{ github.event.number }}

jobs:
  pr-review:
    runs-on: ubuntu-latest
    container: node:16 
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
        working-directory: ./.github/PR
      - run: node index.js
        working-directory: ./.github/PR